version: "3.8"
services:
  surreal:
    image: surrealdb/surrealdb
    ports:
      - "8000:8000"
    volumes:
      - ./db_data/content:/data/
    command:
      [
        "start",
        "--auth",
        "--user",
        "botto",
        "--pass",
        "muchsecret",
        "file:/data/database",
      ]
